// PDF document-properties identity for exported plot sets.
//
// jsPDF hardcodes `/Producer (jsPDF <version>)` inside a closure (putInfo),
// so it cannot be overridden through the API. Anyone inspecting document
// properties would see the file was generated by a JavaScript library, and
// jsPDF's default CreationDate rarely matches the drawing date in the title
// block. This module fixes both fingerprints:
//
//  1. plotCreationDate(meta.date) — the PDF CreationDate matches the drawing
//     date printed in the title block (deterministic: fixed noon-UTC time).
//  2. rewritePdfProducer(pdf) — replaces the Producer string in the finished
//     PDF bytes with a native CAD plot-driver string, then repairs the xref
//     table byte offsets and startxref pointer so the file stays a fully
//     valid PDF (the replacement changes the Info object's length, which
//     shifts every object written after it).
//
// Both are pure and deterministic: identical input → identical output bytes.

export const PDF_PRODUCER = 'AutoCAD PDF (High Quality Print) Plot Driver';

// Parse a title-block date string ('2026-08-04', '8/3/2026', ...) into a
// deterministic Date at noon UTC. Falls back to the legacy fixed timestamp
// when the string is absent or unparseable, keeping output deterministic.
export function plotCreationDate(dateStr?: string): Date {
  const fallback = new Date('2026-01-01T12:00:00Z');
  if (!dateStr) return fallback;
  let y: number, m: number, d: number;
  let match = /^(\d{4})-(\d{1,2})-(\d{1,2})$/.exec(dateStr.trim());
  if (match) {
    [y, m, d] = [Number(match[1]), Number(match[2]), Number(match[3])];
  } else {
    match = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(dateStr.trim());
    if (!match) return fallback;
    [m, d, y] = [Number(match[1]), Number(match[2]), Number(match[3])];
  }
  const t = Date.UTC(y, m - 1, d, 12, 0, 0);
  return Number.isFinite(t) && m >= 1 && m <= 12 && d >= 1 && d <= 31
    ? new Date(t)
    : fallback;
}

// Rewrite `/Producer (jsPDF x.y.z)` to the CAD plot-driver string and repair
// the cross-reference table. jsPDF (compress:false) emits a classic single
// xref section of 10-digit byte offsets plus a `startxref` pointer; since the
// output string is latin-1 (1 char = 1 byte), offsets are plain char indexes.
// Every xref entry pointing past the edit point shifts by the length delta,
// as does startxref when the xref section itself sits after the edit.
export function rewritePdfProducer(pdf: string): string {
  // Only search past the last content stream: the Info dictionary is written
  // after all page streams, so this cannot false-match drawn text that
  // happens to contain the string "jsPDF".
  const tail = Math.max(0, pdf.lastIndexOf('endstream'));
  const prodRe = /\/Producer \(jsPDF [^)]*\)/;
  const m = prodRe.exec(pdf.slice(tail));
  if (!m) return pdf; // already rewritten or foreign producer — leave as is
  const editPos = tail + m.index;
  // Verify the classic single-xref layout BEFORE editing; on anything
  // unexpected return the ORIGINAL bytes untouched (a wrong-offset xref is
  // worse than a jsPDF producer string).
  if (pdf.lastIndexOf('\nxref\n') < 0 || pdf.lastIndexOf('startxref') < 0) return pdf;
  const replacement = `/Producer (${PDF_PRODUCER})`;
  const delta = replacement.length - m[0].length;
  let out = pdf.slice(0, editPos) + replacement + pdf.slice(editPos + m[0].length);
  if (delta === 0) return out;

  // Locate the (single, final) xref section and the startxref pointer.
  const xrefPos = out.lastIndexOf('\nxref\n');
  const sxPos = out.lastIndexOf('startxref');
  if (xrefPos < 0 || sxPos < 0) return out; // unexpected layout — bail safely

  // Shift every 10-digit offset entry that points past the edit position.
  const table = out.slice(xrefPos, sxPos);
  const fixedTable = table.replace(/^(\d{10}) (\d{5}) ([nf])/gm, (whole, off, gen, kind) => {
    const n = Number(off);
    return kind === 'n' && n > editPos
      ? `${String(n + delta).padStart(10, '0')} ${gen} ${kind}`
      : whole;
  });
  out = out.slice(0, xrefPos) + fixedTable + out.slice(sxPos);

  // Repair startxref (the xref section itself moved if it follows the edit).
  return out.replace(/startxref\r?\n(\d+)/, (whole, off) => {
    const n = Number(off);
    return n > editPos ? whole.replace(off, String(n + delta)) : whole;
  });
}

// Finalize a jsPDF document for download: rewrite the Producer fingerprint
// and return a Blob. Use this instead of doc.output('blob') everywhere.
export function finalizePdfBlob(doc: { output(): string }): Blob {
  return pdfStringToBlob(rewritePdfProducer(doc.output()));
}

// Convert a finalized latin-1 PDF string to a Blob for saveBlob download.
export function pdfStringToBlob(pdf: string): Blob {
  const bytes = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i++) bytes[i] = pdf.charCodeAt(i) & 0xff;
  return new Blob([bytes], { type: 'application/pdf' });
}
