// Bakes Manual Placement button icons once. The sidebar references the
// written path strings and does not rescale legend geometry at render time.
//
//   npx tsx scripts/bake-placement-button-icons.ts
import { writeFileSync } from 'fs';
import path from 'path';
import { NEXTERA_GLB_SYMBOLS } from '../client/src/lib/nextera/nexteraGlbSymbols';
import { ECI_LEGEND_GLYPHS } from '../client/src/lib/nextera/eciLegendGlyphs';
import { EQUIP_GLYPHS } from '../client/src/lib/nextera/equipGlyphs';

const SIZE = 32;
const PAD = 2;

type Ring = readonly (readonly number[])[];

function ringsFromGlb(key: string): Ring[] {
  const symbol = NEXTERA_GLB_SYMBOLS[key];
  if (!symbol) throw new Error(`Missing GLB legend symbol ${key}`);
  return symbol.polys.flat();
}

function ringsFromEci(key: string): Ring[] {
  const glyph = ECI_LEGEND_GLYPHS[key];
  if (!glyph) throw new Error(`Missing ECI legend glyph ${key}`);
  return [...glyph.black.flat(), ...glyph.gray.flat()];
}

function ringsFromEquipGlyph(key: string): Ring[] {
  const glyph = EQUIP_GLYPHS[key];
  if (!glyph) throw new Error(`Missing equipment glyph ${key}`);
  return [...glyph.outline, ...glyph.detail];
}

/** Fit rings into a SIZE×SIZE icon, y flipped for SVG. Quantized once. */
function iconPath(rings: Ring[]): string {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const ring of rings) {
    for (const p of ring) {
      const x = p[0], y = p[1];
      if (x < minX) minX = x;
      if (y < minY) minY = y;
      if (x > maxX) maxX = x;
      if (y > maxY) maxY = y;
    }
  }
  const bw = Math.max(maxX - minX, 1e-6);
  const bh = Math.max(maxY - minY, 1e-6);
  const inner = SIZE - PAD * 2;
  const scale = Math.min(inner / bw, inner / bh);
  const ox = PAD + (inner - bw * scale) / 2;
  const oy = PAD + (inner - bh * scale) / 2;
  const q = (v: number) => Math.round(v * 10) / 10;
  let d = '';
  for (const ring of rings) {
    if (ring.length < 3) continue;
    ring.forEach((p, i) => {
      const x = q(ox + (p[0] - minX) * scale);
      const y = q(oy + (maxY - p[1]) * scale);
      d += i === 0 ? `M${x} ${y}` : `L${x} ${y}`;
    });
    d += 'Z';
  }
  return d;
}

// Simple stand-ins. These are not legend traces.
const PLACEHOLDERS: Record<string, string> = {
  auxSwitchPanel: 'M6 5H26V27H6Z M16 5V27 M9 10H13 M19 10H23 M9 16H13 M19 16H23',
  road: 'M4 12H28V20H4Z M8 16H24',
  gate: 'M5 6V26 M9 8H23V24 M27 6V26',
};

const icons: Record<string, string> = {
  pcsGe: iconPath(ringsFromGlb('geFlex')),
  pcsPe: iconPath(ringsFromGlb('peInverter')),
  batteryGe: iconPath(ringsFromGlb('lgLinkGe')),
  batteryPe: iconPath(ringsFromGlb('lgLinkPe')),
  auxTransformer: iconPath(ringsFromGlb('auxTransformer')),
  auxSwitchgear: iconPath(ringsFromGlb('auxDistCenter')),
  commsCabinetGe: iconPath(ringsFromGlb('commsCabinetGe')),
  commsCabinetPe: iconPath(ringsFromGlb('commsCabinetPe')),
  fiberPatchPanel: iconPath(ringsFromEci('fiberJunctionBox')),
  fireControlPanel: iconPath(ringsFromEquipGlyph('fireControlPanel')),
  ...PLACEHOLDERS,
};

const body = `// Generated by scripts/bake-placement-button-icons.ts — do not edit.
// Each value is a 32×32 SVG path, scaled once from the legend (or a placeholder).
export const PLACEMENT_BUTTON_ICON_SIZE = ${SIZE};

export const PLACEMENT_BUTTON_ICONS: Record<string, string> = {
${Object.entries(icons).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join('\n')}
};
`;

const out = path.resolve('client/src/lib/nextera/placementButtonIcons.ts');
writeFileSync(out, body);
console.log(`Wrote ${out} (${Object.keys(icons).length} icons)`);
